// Words for today: the quotes, shared by the app (index.html) and the service worker (sw.js,
// which picks one for a daily notification). Licences and translators: see About in the app.
// cont:1 marks quotes about carrying on / beginning again.
const QUOTES=[
  // Carrying on and beginning again (cont:1, shown when it's been a while since your last sit).
  {t:'He who formerly was reckless and afterwards became sober, brightens up this world, like the moon when freed from clouds.',a:'Dhammapada 172',cont:1},
  {t:'By rousing himself, by earnestness, by restraint and control, the wise man may make for himself an island which no flood can overwhelm.',a:'Dhammapada 25',cont:1},
  {t:'Let a wise man blow off the impurities of his self, as a smith blows off the impurities of silver one by one, little by little, and from time to time.',a:'Dhammapada 239',cont:1},
  {t:'Don’t be a fool: for once, just sit tight.',a:'Patrul Rinpoche, Advice from Me to Myself',cont:1},
  {t:'The way to practice is to apply yourself to something appropriate to your abilities.',a:'Patrul Rinpoche, Heart Advice for Practitioners',cont:1},
  {t:'Limit yourself to just a few activities and undertake them all with diligence.',a:'Chatral Rinpoche, Words of Advice',cont:1},
  {t:'The best time to plant a tree was twenty years ago. The second best time is now.',a:'Proverb, origin unknown',cont:1},
  // From the practice liturgy
  {t:'May all beings have happiness and the causes of happiness. May all beings be free from suffering and its causes.',a:'The Four Immeasurables'},
  {t:'May the precious bodhicitta take birth where it is not yet existing; where it exists may it never wane, but continuously and ever increase.',a:'Aspiration for bodhicitta'},
  {t:'Detachment is the foot of meditation. Devotion is the head of meditation. Unwavering attention is the body of meditation.',a:'Dorje Chang Tungma'},
  {t:'Grant your blessings so that my mind may be one with the Dharma.',a:'The Four Dharmas of Gampopa'},
  {t:'Grant your blessings so that Dharma may progress along the path.',a:'The Four Dharmas of Gampopa'},
  {t:'Grant your blessings so that the path may clarify confusion.',a:'The Four Dharmas of Gampopa'},
  {t:'Grant your blessings so that confusion may dawn as wisdom.',a:'The Four Dharmas of Gampopa'},
  {t:'Through this virtue may omniscience be attained, and may every defilement be overcome.',a:'Dedication of merit'},
  // Lineage
  {t:'Don’t recall. Don’t imagine. Don’t think. Don’t examine. Don’t control. Rest.',a:'Tilopa’s six words of advice'},
  {t:'Son, it is not appearances that bind you; it is grasping.\nCut through your attachment, Nāropa.',a:'Tilopa'},
  {t:'My view is higher than the sky,\nMy attention to the karmic process finer than grains of flour.',a:'Guru Rinpoche'},
  {t:'For as long as space endures, and for as long as living beings remain, until then may I too abide to dispel the misery of the world.',a:'Śāntideva, The Way of the Bodhisattva 10.55'},
  // Śāntideva, Bodhicaryāvatāra, tr. L. D. Barnett, "The Path of Light" (1909, public domain)
  {t:'As in the night, amidst the gross darkness of the clouds, the lightning shews for an instant its radiance, so by the grace of the Enlightened it may hap that the mind of man turn for an instant to holy works.',a:'Śāntideva, The Path of Light, ch. 1'},
  {t:'Eager to escape sorrow, men rush into sorrow; from desire of happiness they blindly slay their own happiness, enemies to themselves.',a:'Śāntideva, The Path of Light, ch. 1'},
  {t:'May I be a balm to the sick, their healer and servitor, until sickness come never again.',a:'Śāntideva, The Path of Light, ch. 3'},
  {t:'I would be a protector of the unprotected, a guide of wayfarers, a ship, a dyke, and a bridge for them who seek the further Shore; a lamp for them who need a lamp, a bed for them who need a bed.',a:'Śāntideva, The Path of Light, ch. 3'},
  {t:'This Thought of Enlightenment has arisen within me I know not how, even as a gem might be gotten by a blind man from a dunghill.',a:'Śāntideva, The Path of Light, ch. 3'},
  {t:'How many can I slay of the wicked, who are measureless as space? But when the thought of wrath is slain, all my foes are slain.',a:'Śāntideva, The Path of Light, ch. 5'},
  {t:'Whence can be found leather enough to cover the whole earth? But with a single leather shoe the whole ground is covered. In like manner the forces without me I cannot control; but I will control the thought within me.',a:'Śāntideva, The Path of Light, ch. 5'},
  {t:'There is no guilt equal to hatred, no mortification equal to long-suffering.',a:'Śāntideva, The Path of Light, ch. 6'},
  {t:'While the arrow of hate is in the heart, none can have a peaceful mind in equipoise, or feel the joy of kindliness, none can win sleep or calm.',a:'Śāntideva, The Path of Light, ch. 6'},
  {t:'Form is emptiness, emptiness is form.',a:'The Heart Sūtra'},
  {t:'Decay is inherent in all component things. Work out your salvation with diligence.',a:'The Buddha’s last words',cont:1},
  // The Dhammapada, tr. F. Max Müller (1881)
  {t:'All that we are is the result of what we have thought: it is founded on our thoughts, it is made up of our thoughts.',a:'Dhammapada 1'},
  {t:'If a man speaks or acts with a pure thought, happiness follows him, like a shadow that never leaves him.',a:'Dhammapada 2'},
  {t:'Hatred does not cease by hatred at any time: hatred ceases by love. This is an old rule.',a:'Dhammapada 5'},
  {t:'As rain breaks through an ill-thatched house, passion will break through an unreflecting mind.',a:'Dhammapada 13'},
  {t:'As rain does not break through a well-thatched house, passion will not break through a well-reflecting mind.',a:'Dhammapada 14'},
  {t:'Earnestness is the path of immortality, thoughtlessness the path of death.',a:'Dhammapada 21'},
  {t:'It is good to tame the mind, which is difficult to hold in and flighty, rushing wherever it listeth; a tamed mind brings happiness.',a:'Dhammapada 35'},
  {t:'As the bee collects nectar and departs without injuring the flower, or its colour or scent, so let a sage dwell in his village.',a:'Dhammapada 49'},
  {t:'Not the perversities of others, not their sins of commission or omission, but his own misdeeds and negligences should a sage take notice of.',a:'Dhammapada 50'},
  {t:'Like a beautiful flower, full of colour, but without scent, are the fine but fruitless words of him who does not act accordingly.',a:'Dhammapada 51'},
  {t:'As a solid rock is not shaken by the wind, wise people falter not amidst blame and praise.',a:'Dhammapada 81'},
  {t:'Even though a speech be a thousand words, but made up of senseless words, one word of sense is better, which if a man hears, he becomes quiet.',a:'Dhammapada 100'},
  {t:'If one man conquer in battle a thousand times thousand men, and if another conquer himself, he is the greatest of conquerors.',a:'Dhammapada 103'},
  {t:'Let no man think lightly of good, saying in his heart, It will not benefit me. Even by the falling of water-drops a water-pot is filled; the wise man becomes full of good, even if he gather it little by little.',a:'Dhammapada 122',cont:1},
  {t:'Self is the lord of self; who else could be the lord?',a:'Dhammapada 160'},
  {t:'By oneself the evil is done, by oneself one suffers; by oneself evil is left undone, by oneself one is purified.',a:'Dhammapada 165'},
  {t:'Not to commit any sin, to do good, and to purify one’s mind: that is the teaching of all the Awakened.',a:'Dhammapada 183'},
  {t:'Let us live happily then, not hating those who hate us.',a:'Dhammapada 197'},
  {t:'Health is the greatest of gifts, contentment the best riches; trust is the best of relationships, Nirvana the highest happiness.',a:'Dhammapada 204'},
  {t:'Let a man overcome anger by love, let him overcome evil by good; let him overcome the greedy by liberality, the liar by truth.',a:'Dhammapada 223'},
  {t:'The fault of others is easily perceived, but that of oneself is difficult to perceive.',a:'Dhammapada 252'},
  {t:'You yourself must make an effort. The Tathāgatas are only preachers.',a:'Dhammapada 276',cont:1},
  {t:'Through zeal knowledge is gotten, through lack of zeal knowledge is lost.',a:'Dhammapada 282'},

  // ── From Lotsawa House (lotsawahouse.org), licensed CC BY-NC 4.0, quoted word for word.
  // Translators are named in each comment and credited in About. Tilopa and Guru Rinpoche above
  // are also Lotsawa House (tr. Adam Pearcey 2004, rev. 2025).
  // Patrul Rinpoche, Advice from Me to Myself, tr. Constance Wilkinson
  {t:'If you let go of everything—\nEverything, everything—\nThat’s the real point!',a:'Patrul Rinpoche, Advice from Me to Myself'},
  {t:'Thinking about the hundred plans you want to accomplish,\nWith never enough time to finish them,\nJust weighs down your mind.',a:'Patrul Rinpoche, Advice from Me to Myself'},
  {t:'Don’t be a fool: for once, just sit tight.',a:'Patrul Rinpoche, Advice from Me to Myself'},
  {t:'Giving teachings on meditation texts\nWithout yourself having\nGained actual experience through practice,\nIs like reciting a dance-manual out loud\nAnd thinking that’s the same as actually dancing.',a:'Patrul Rinpoche, Advice from Me to Myself'},
  {t:'Even though you don’t know how to practice, just let go of everything—that’s what I really want to say.',a:'Patrul Rinpoche, Advice from Me to Myself'},
  // Patrul Rinpoche, Advice in Sets of Three, tr. Adam Pearcey 2021
  {t:'Three things must not be forgotten:\nThe gracious guru,\nThe compassionate Buddha,\nAnd mindfulness and vigilance.',a:'Patrul Rinpoche, Advice in Sets of Three'},
  {t:'Three things must be present:\nThe mind in the body,\nThe body on its seat,\nAnd the mind in relaxation.',a:'Patrul Rinpoche, Advice in Sets of Three'},
  {t:'Three things are best kept under control:\nYour mouth when at gatherings,\nYour hands when alone,\nAnd your mind at all times.',a:'Patrul Rinpoche, Advice in Sets of Three'},
  {t:'Three things must be kept secret:\nYour own virtues,\nThe faults of others,\nAnd plans for the future.',a:'Patrul Rinpoche, Advice in Sets of Three'},
  {t:'Always examine yourself. Don’t forget this.',a:'Patrul Rinpoche, Advice in Sets of Three'},
  // Dilgo Khyentse Rinpoche, Heart Advice in Four Lines, Rigpa Translations
  {t:'Do not forget the guru;\nPray to him at all times.',a:'Dilgo Khyentse Rinpoche, Heart Advice in Four Lines'},
  {t:'Do not let your mind be distracted;\nLook into its very essence.',a:'Dilgo Khyentse Rinpoche, Heart Advice in Four Lines'},
  {t:'Do not forget death;\nLet it spur you on to Dharma.',a:'Dilgo Khyentse Rinpoche, Heart Advice in Four Lines'},
  {t:'Do not forget sentient beings;\nWith compassion dedicate your merit to them and make prayers of aspiration.',a:'Dilgo Khyentse Rinpoche, Heart Advice in Four Lines'},
  // Dilgo Khyentse Rinpoche, Advice to three-year retreatants, tr. Adam Pearcey 2007
  {t:'In Dharma practice, the most important thing is motivation. If it is motivated by the wish to benefit all beings, then even a single prostration or a single recitation of the hundred-syllable mantra will yield inexhaustible merit.',a:'Dilgo Khyentse Rinpoche'},
  {t:'Even if you were to practise day and night with unflagging diligence for a full twelve years and still fail to have even one good dream, you must never lose heart.',a:'Dilgo Khyentse Rinpoche',cont:1},
  {t:'Understand this: it is more important to take to heart the key instructions than to receive a great many teachings.',a:'Dilgo Khyentse Rinpoche'},
  {t:'Without genuine compassion there is simply no possibility of reaching buddhahood.',a:'Dilgo Khyentse Rinpoche'},
  {t:'To recite even a single maṇi mantra is of inconceivable benefit, so dedicate it for the sake of all who live.',a:'Dilgo Khyentse Rinpoche'},
  {t:'When looking into the nature of mind, don’t expect to gain some exceptionally high or profound realization, or to see anything new. Nor should you hesitate or doubt your ability to meditate.',a:'Dilgo Khyentse Rinpoche'},
  {t:'When you are approaching the end of the Dharma\nContinue ceaselessly, without any highs or lows,\nAnd without hopes for signs of swift attainment,\nEnsure your practice endures as long as you do!',a:'Milarepa, quoted by Dilgo Khyentse Rinpoche'},
  // 3rd Karmapa Rangjung Dorje, Aspiration of the Mahāmudrā of Definitive Meaning, tr. Adam Pearcey 2020
  {t:'Having found supreme freedom and advantage, with faith, diligence, and wisdom,\nMay I rely upon excellent spiritual friends, receive the elixir of instruction,\nAnd accomplish it in the proper way without any impediment,\nPutting the genuine Dharma into practice throughout all my lives.',a:'The 3rd Karmapa, Mahāmudrā Aspiration'},
  {t:'All phenomena are but apparitions of the mind;\nMind itself is without mind, empty of mind’s essence—\nEmpty yet unrestricted, appearing in any way at all.\nHaving examined it well, may I determine the basis.',a:'The 3rd Karmapa, Mahāmudrā Aspiration'},
  {t:'Not realizing this, I drift about in saṃsāra’s ocean.\nWhen I do realize it, buddhahood lies nowhere else.\nEverything is this; there is nothing else besides.',a:'The 3rd Karmapa, Mahāmudrā Aspiration'},
  {t:'Appearances are mind; emptiness is also the mind.\nRealization is mind; delusion too is one’s own mind.\nWhat’s arisen is mind; what’s ceased is also mind.\nMay I eliminate all misconceptions within the mind.',a:'The 3rd Karmapa, Mahāmudrā Aspiration'},
  {t:'Unspoilt by deliberate, mind-fabricated meditation,\nAnd unswayed by the winds of ordinary preoccupation,\nMay I learn how to settle naturally without contrivance.',a:'The 3rd Karmapa, Mahāmudrā Aspiration'},
  {t:'Looking at objects, I see them as objectless mind;\nLooking at mind, mind is absent, empty of essence;\nLooking at both, duality is liberated there and then—\nMay I realize mind’s true nature, which is clear light.',a:'The 3rd Karmapa, Mahāmudrā Aspiration'},
  // 15th Karmapa Khakhyab Dorje, Advice for Orgyen Tsomo, tr. Abraham Ta-Quan 2020 (the four thoughts)
  {t:'Think of the future and turn your back on this world.\nThink of the effects of actions and keep vows and samaya.\nThink of the advantages and apply yourself to the sacred Dharma.\nThink of impermanence and develop perseverance in the practice.\nThink of its flaws and avoid attachment to the ocean of saṃsāra.',a:'The 15th Karmapa, Advice for Orgyen Tsomo'},
  // Gampopa, tr. Adam Pearcey · Milarepa, Rigpa Translations and tr. Adam Pearcey · Marpa, tr. Sean Ross 2023
  {t:'Unless you practise Dharma according to the Dharma, Dharma itself will become the cause of lower rebirth.',a:'Gampopa'},
  {t:'In horror of death, I took to the mountains—\nAgain and again I meditated on the uncertainty of the hour of death,\nCapturing the fortress of the deathless unending nature of mind.\nNow all fear of death is over and done.',a:'Milarepa'},
  {t:'Between the hermit meditating in a rocky cave\nAnd the sponsor who provides his sustenance\nIs a connection that will bring both to buddhahood.\nThe heart of that connection is dedication of merit.',a:'Milarepa'},
  {t:'Worldly beings grasp death as their enemy, whereas yogis, on the basis of the guru’s oral instructions, will at the time of death, or in the bardo, take it as a friend.',a:'Marpa, The Nail of Taking Death as a Friend'},
  // Nāgārjuna, Precious Garland, tr. Adam Pearcey 2004, rev. 2025
  {t:'As long as the aggregates are conceived,\nThere will be a conception of “I”,\nAnd when there is a conception of “I”,\nThere’s karma, and from that, rebirth.',a:'Nāgārjuna, Precious Garland 1.35'},
  {t:'If we ourselves and all the world\nWish for unsurpassed enlightenment,\nIts basis is bodhicitta\nStable as the king of mountains,\nCompassion reaching out in all directions,\nAnd wisdom that transcends duality.',a:'Nāgārjuna, Precious Garland 2.73–74'},
  {t:'Causes of death are numerous,\nWhile causes of life are few indeed,\nAnd even those may cause death;\nSo practise Dharma at all times.',a:'Nāgārjuna, Precious Garland 3.78'},
  {t:'Offerings of three hundred pots of food\nMade three times each and every day\nCould not match even a portion of the merit\nGained from just a single moment’s loving kindness.',a:'Nāgārjuna, Precious Garland 3.83'},
  // Śāntideva, Bodhicaryāvatāra ch. 1, tr. Adam Pearcey 2007
  {t:'This free and well-favoured human form is difficult to obtain.\nNow that we have the chance to realise the full human potential,\nIf we don’t make good use of this opportunity,\nHow could we possibly expect to have such a chance again?',a:'Śāntideva, Bodhicaryāvatāra 1.4'},
  {t:'Those who long to triumph over life’s distress,\nAnd who wish to put an end to others’ sorrows,\nThose who seek to experience abundant joys—\nLet them never turn their backs on bodhicitta.',a:'Śāntideva, Bodhicaryāvatāra 1.8'},
  {t:'All other virtues are like the plantain tree:\nThey bear their fruit, and then they are no more.\nYet constantly the marvellous tree of bodhicitta\nYields fruit and, undiminished, grows for evermore.',a:'Śāntideva, Bodhicaryāvatāra 1.12'},
  // Candragomin, Letter to a Disciple 63, tr. Adam Pearcey
  {t:'This human life is more valuable even than a wishing-gem—\nWho could let it go to waste and fail to bear its fruit?',a:'Candragomin, Letter to a Disciple'},
  // Atiśa: tr. Adam Pearcey; The Bodhisattva’s Garland of Jewels, Rigpa Translations 2008
  {t:'The best spiritual guide is one who attacks your hidden faults.\nThe best instructions are those that directly target such faults.',a:'Atiśa'},
  {t:'Be done with doubt and indecision,\nAnd embrace your practice with all your heart.',a:'Atiśa, The Bodhisattva’s Garland of Jewels'},
  {t:'Make plain your own failings,\nBut don’t look for faults in others.\nMake known the good points of others,\nBut keep quiet about your own best qualities.',a:'Atiśa, The Bodhisattva’s Garland of Jewels'},
  {t:'Whenever you see any sentient beings,\nRegard them as your parents or your children.',a:'Atiśa, The Bodhisattva’s Garland of Jewels'},
  {t:'Drop any feelings of hostility or ill will,\nAnd be happy, wherever you choose to go.',a:'Atiśa, The Bodhisattva’s Garland of Jewels'},
  // Indian and Tibetan masters, tr. Adam Pearcey (2004, rev. 2025 unless noted)
  {t:'As you look and look into the sky-like nature\nThat has always been pure, seeing recedes.',a:'Saraha'},
  {t:'To believe things are real is to be like cattle;\nBut to believe they are unreal is yet more foolish.',a:'Saraha'},
  {t:'Mind’s nature is and always has been Buddha.\nIt has neither birth nor cessation, like space.',a:'Garab Dorje'},
  {t:'Unstained by objects of perception,\nUnspoilt by apprehending thought,\nSustaining naked, empty awareness—\nThis is the wisdom of all the buddhas!',a:'Guru Rinpoche'},
  {t:'Tightly focused and loosely relaxed:\nTherein lies a key point of the view.',a:'Machik Labdrön'},
  {t:'Generating bodhicitta at the beginning, having no reference in the main part,\nAnd dedicating merit at the conclusion—these, when fully embraced,\nConstitute three vital principles of progression on the path to liberation.',a:'Longchenpa'},
  {t:'If you don’t begin with thorough analysis,\nHow will perfect certainty ever arise?',a:'Mipham Rinpoche, Beacon of Certainty'},
  {t:'Love is the seed of this abundant harvest of buddhahood.\nIt is like the water that causes growth and expansion,\nAnd it ripens into the state of lasting enjoyment.\nTherefore, at the outset, I praise compassion!',a:'Candrakīrti, Introduction to the Middle Way 1.2'},
  {t:'At first, turn away from non-virtue,\nIn the middle, dispel misconceptions of self,\nFinally, go beyond all philosophical views—\nOne who understands this is wise indeed.',a:'Āryadeva, Four Hundred Verses 8.15'},
  {t:'Whoever sees the nature of one thing\nIs said to see the nature of everything.',a:'Āryadeva, Four Hundred Verses 8.16'},
  {t:'Illness must be understood, its causes eliminated;\nWellbeing must be attained, and medicine taken.\nLikewise, suffering, its causes, their cessation and the path\nMust in turn be understood, eliminated, realized and relied upon.',a:'Maitreya, Sublime Continuum 4.55'},
];
